<Project Sdk="Microsoft.NET.Sdk.Web"><ItemGroup><ProjectReference Include="../School.Shared/School.Shared.csproj"/><ProjectReference Include="../School.Migrations.Sqlite/School.Migrations.Sqlite.csproj"/><ProjectReference Include="../School.Migrations.Postgres/School.Migrations.Postgres.csproj"/></ItemGroup></Project>
