import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { SchoolClient, SchoolError, type User, type Student, type School, type SchoolApplication, type StaffApplication, type Balance, type RequestEvent } from '@school-portal/browser-sdk';
import './styles.css';

const messages: Record<string,string> = {
  INVALID_CREDENTIALS:'Check your email and password, and make sure your email is verified.',
  SESSION_EXPIRED:'Your session has ended. Please sign in again.', SESSION_REQUIRED:'Please sign in to continue.',
  PASSWORD_POLICY:'Choose a passphrase with 15–128 characters.', LINK_INVALID:'This link has expired or was already used. Request a new one.',
  RATE_LIMITED:'Too many attempts. Please wait before trying again.', RECORD_NOT_FOUND:'This record is not available to your account.',
  VERSION_CONFLICT:'This application was already updated. Refresh the list.', APPLICATION_ALREADY_EXISTS:'An application for this student, school and year already exists.',
  CLIENT_TIMEOUT:'The request timed out. A submission may have completed. Check your applications before retrying.',
  NETWORK_ERROR:'We could not reach the server. Check your connection.', SERVICE_UNAVAILABLE:'The service is temporarily unavailable.',
  SECURITY_STATE_UNAVAILABLE:'The secure session service is unavailable. Please try again later.', ACCESS_DENIED:'Your account does not have permission for this action.',
  IDEMPOTENCY_CONFLICT:'This request reference was already used with different details.', VALIDATION_FAILED:'Please check the entered details.',
  BFF_SERVICE_AUTH_FAILED:'The server could not authenticate its backend request. Please contact support with the reference below.'
};
function CampusArt() { return <svg className="campus-art" viewBox="0 0 500 310" role="img" aria-label="Illustration of a school among trees"><circle cx="385" cy="60" r="35" fill="#f3c973"/><path d="M0 280Q130 225 245 262T500 254V310H0" fill="#c7dac8"/><path d="M105 132L251 55L397 132Z" fill="#163f37"/><rect x="123" y="130" width="255" height="141" rx="3" fill="#f1e9d8"/><rect x="205" y="111" width="90" height="160" fill="#fffaf0"/><path d="M195 111L250 80L306 111" fill="#3c6d56"/><rect x="232" y="208" width="38" height="63" rx="19" fill="#23493e"/>{[147,177,314,344].map(x=><React.Fragment key={x}><rect x={x} y="155" width="18" height="27" rx="2" fill="#82a99d"/><rect x={x} y="201" width="18" height="27" rx="2" fill="#82a99d"/></React.Fragment>)}<circle cx="250" cy="145" r="17" fill="#e5c17b"/><path d="M250 134V145L258 150" stroke="#163f37" strokeWidth="3" fill="none"/><path d="M216 310L233 271H270L287 310" fill="#e8d5b2"/>{[65,437].map(x=><g key={x}><rect x={x-4} y="210" width="8" height="62" fill="#867451"/><ellipse cx={x} cy="197" rx="31" ry="46" fill="#5e8b63"/><ellipse cx={x-10} cy="176" rx="22" ry="35" fill="#7fa174"/></g>)}<path d="M250 54V19" stroke="#163f37" strokeWidth="4"/><path d="M252 20H287L278 30L287 40H252" fill="#d99058"/></svg>; }
function App() {
  const [events,setEvents] = useState<RequestEvent[]>([]);
  const clientRef = useRef<SchoolClient | null>(null);
  if (!clientRef.current) clientRef.current = new SchoolClient({onRequest:e => { if(e.stage === 'complete' || e.stage === 'error') setEvents(v=>[e,...v].slice(0,12)); }});
  const client = clientRef.current;
  const [user,setUser] = useState<User>(); const [initializing,setInitializing] = useState(true);
  const [view,setView] = useState('Overview'); const [authMode,setAuthMode] = useState('login');
  const [students,setStudents] = useState<Student[]>([]); const [schools,setSchools] = useState<School[]>([]);
  const [applications,setApplications] = useState<SchoolApplication[]>([]); const [staff,setStaff] = useState<StaffApplication[]>([]);
  const [balances,setBalances] = useState<Balance[]>([]); const [busy,setBusy] = useState(false);
  const [error,setError] = useState(''); const [notice,setNotice] = useState('');
  const [actionLink] = useState(() => new URLSearchParams(location.hash.slice(1)));
  const [resetToken,setResetToken] = useState(actionLink.get('reset') ?? '');
  const [selection,setSelection] = useState(''); const [selectedSchool,setSelectedSchool] = useState('oakwood');
  const submission = useRef({key:'',id:crypto.randomUUID() as string});
  const studentSubmission = useRef({key:'',id:crypto.randomUUID() as string});
  function failure(e: unknown) {
    if (e instanceof SchoolError) {
      setError((messages[e.code] ?? 'We could not complete that request. Please try again.') + (e.traceId ? ` Reference: ${e.traceId}` : ''));
      if (['SESSION_EXPIRED','SESSION_REQUIRED','SESSION_CONTEXT_REQUIRED'].includes(e.code)) { setUser(undefined); setStudents([]); setBalances([]); setApplications([]); setStaff([]); }
    } else setError('Something went wrong. Please try again.');
  }
  async function run(fn:()=>Promise<void>) { if(busy)return; setBusy(true);setError('');setNotice('');try{await fn();}catch(e){failure(e);}finally{setBusy(false);} }
  async function refresh(current = user) {
    if(!current)return;
    if(current.role === 'staff') { setStaff(await client.staffApplications()); return; }
    const [s,c,a] = await Promise.all([client.students(),client.schools(),client.applications()]);
    setStudents(s);setSchools(c);setApplications(a);setSelection(previous => previous || s[0]?.id || '');
    setBalances(await Promise.all(s.map(x=>client.balance(x.id))));
  }
  useEffect(()=>{
    history.replaceState(null,'',location.pathname);
    void (async()=>{
      try {
        const verify = actionLink.get('verify');
        if(verify) {setAuthMode('activate');return;}
        if(resetToken){setAuthMode('reset');return;}
        const current=await client.restore();setUser(current);setView(current.role === 'staff'?'Review queue':'Overview');await refresh(current);
      } catch(e) { if(!(e instanceof SchoolError && ['SESSION_REQUIRED','SESSION_EXPIRED'].includes(e.code)))failure(e); }
      finally{setInitializing(false);}
    })();
  },[]);
  async function authenticate(event:React.FormEvent<HTMLFormElement>) {
    event.preventDefault();const form=new FormData(event.currentTarget);const email=String(form.get('email')??'');const password=String(form.get('password')??'');
    await run(async()=>{
      if(authMode==='register'){setNotice((await client.register({email})).message);setAuthMode('login');}
      else if(authMode==='activate'){setNotice((await client.verifyEmail(actionLink.get('verify')!,String(form.get('name')),password)).message);setAuthMode('login');}
      else if(authMode==='forgot'){setNotice((await client.forgotPassword(email)).message);}
      else if(authMode==='reset'){setNotice((await client.resetPassword(resetToken,password)).message);setResetToken('');setAuthMode('login');}
      else{const current=await client.login(email,password);setUser(current);setView(current.role==='staff'?'Review queue':'Overview');await refresh(current);}
    });
  }
  const alerts=<>{error&&<div className="alert error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}{notice&&<div className="alert success" role="status">{notice}</div>}</>;
  const brand=<div className="brand"><span className="brand-icon">S<span>·</span></span><span>school<span className="brand-light">portal</span></span></div>;
  if(initializing)return <main className="loading">{brand}<p>Opening your secure workspace…</p></main>;
  if(!user)return <main className="auth-page"><section className="auth-story">{brand}<div className="story-copy"><span className="eyebrow">A PLACE TO GROW</span><h1>Big futures.<br/>Simple beginnings.</h1><p>Your family’s school journey, together in one place.</p><CampusArt/><div className="story-points"><span>01 &nbsp; Add your student</span><span>02 &nbsp; Find a school</span><span>03 &nbsp; Follow their journey</span></div></div><small>School Portal · Academic year 2026–2027</small></section><section className="auth-panel"><div className="auth-form"><span className="eyebrow">YOUR SCHOOL COMMUNITY</span><h2>{authMode==='register'?'Start your journey':authMode==='forgot'?'Forgot your password?':authMode==='reset'?'Choose a new password':authMode==='activate'?'Activate your account':'Welcome back.'}</h2><p className="muted">{authMode==='register'?'Create a parent account. We’ll send you a verification link.':authMode==='forgot'?'We’ll email a link if your account is eligible.':authMode==='reset'?'A long, memorable passphrase works best.':authMode==='activate'?'Your email is confirmed. Choose your name and password to finish.':'Sign in to manage students and school applications.'}</p>{alerts}<form onSubmit={authenticate} key={authMode}>{authMode==='activate'&&<label>Your name<input name="name" autoComplete="name" maxLength={80} required placeholder="Full name"/></label>}{authMode!=='reset'&&authMode!=='activate'&&<label>Email address<input name="email" type="email" autoComplete="email" maxLength={254} required placeholder="you@example.com"/></label>}{authMode!=='forgot'&&authMode!=='register'&&<label>Password<input name="password" type="password" autoComplete={authMode==='login'?'current-password':'new-password'} minLength={authMode==='login'?1:15} maxLength={128} required placeholder={authMode==='login'?'Your password':'At least 15 characters'}/></label>}<button className="primary full" disabled={busy}>{busy?'Please wait…':authMode==='register'?'Create account →':authMode==='forgot'?'Send reset link':authMode==='reset'?'Update password':authMode==='activate'?'Activate account →':'Sign in →'}</button></form>{authMode==='login'&&<button className="text-button" onClick={()=>{setAuthMode('forgot');setError('');}}>Forgot password?</button>}<div className="auth-switch">{authMode==='login'?'New to School Portal? ':'Already have an account? '}<button className="text-button" onClick={()=>{setAuthMode(authMode==='login'?'register':'login');setError('');}}>{authMode==='login'?'Create an account':'Sign in'}</button></div><div className="secure-note"><span>◈</span> Your session is protected. Your account stays yours.</div></div></section></main>;
  const navigation=user.role==='staff'?['Review queue','Request activity']:['Overview','My students','Applications','Find a school','Request activity'];
  return <div className="workspace"><aside className="sidebar">{brand}<div className="nav-label">{user.role==='staff'?'ADMISSIONS WORKSPACE':'PARENT WORKSPACE'}</div><nav aria-label="Main navigation">{navigation.map((item,i)=><button key={item} className={view===item?'active':''} onClick={()=>{setView(item);setError('');setNotice('');}}><span aria-hidden="true">{['◫','◎','▤','⌂','↗'][i]}</span>{item}</button>)}</nav><div className="sidebar-bottom"><div className="session-pill"><i/> Secure session active</div><p>Growing possibilities.<br/>One school day at a time.</p><button className="logout" disabled={busy} onClick={()=>run(async()=>{await client.logout();setUser(undefined);setStudents([]);setApplications([]);setBalances([]);setStaff([]);setEvents([]);})}>Sign out ↗</button></div></aside><div className="main-column"><header className="topbar"><span>School Portal <span className="slash">/</span> {view}</span><div className="account"><span className="year">2026–2027</span><span className="avatar">{user.name.slice(0,1).toUpperCase()}</span><div><strong>{user.name}</strong><small>{user.role==='staff'?'Admissions team':'Parent account'}</small></div></div></header><main className="content">{alerts}<div className="page-heading"><div><span className="eyebrow">{user.role==='staff'?'ADMISSIONS':'YOUR FAMILY, CONNECTED'}</span><h1>{view==='Overview'?`Hello, ${user.name.split(' ')[0]}.`:view}</h1><p className="muted">{view==='Overview'?'A little organization today. A bright tomorrow.':view==='My students'?'A home for every student’s next chapter.':view==='Applications'?'Start an application and follow its progress.':view==='Review queue'?'Review submissions and record an admissions decision.':view==='Request activity'?'Recent request outcomes from this tab. Secrets and payloads are never displayed.':'Explore the schools in your community.'}</p></div><button className="secondary" disabled={busy} onClick={()=>run(()=>refresh())}>↻ Refresh</button></div>
    {view==='Overview'&&<><section className="welcome-card"><div><span className="eyebrow">THE NEXT CHAPTER STARTS HERE</span><h2>Room to learn.<br/>Space to belong.</h2><p>Find their school. Follow their progress.<br/>We’ll keep the details together.</p><button className="primary" onClick={()=>setView(students.length?'Applications':'My students')}>{students.length?'Start an application':'Add your first student'} →</button></div><CampusArt/></section><div className="stats"><Stat number={students.length} label="My students" detail="Connected to your account"/><Stat number={applications.length} label="Applications" detail="All your submissions"/><Stat number={applications.filter(a=>a.status==='Submitted').length} label="In review" detail="Waiting for a school decision"/></div><section className="card"><div className="section-heading"><h2>Your students</h2><button className="text-button" onClick={()=>setView('My students')}>Manage students ↗</button></div>{students.length?<div className="student-grid">{students.map(s=><StudentCard key={s.id} student={s} balance={balances.find(b=>b.studentId===s.id)}/>)}</div>:<Empty title="Their journey starts with a name." text="Add a student to see their details and start a school application."/>}</section></>}
    {view==='My students'&&<div className="two-column"><section className="card"><h2>Your students</h2><div className="student-grid">{students.map(s=><StudentCard key={s.id} student={s} balance={balances.find(b=>b.studentId===s.id)}/>)}</div>{!students.length&&<Empty title="No students yet" text="Create a student profile using the form."/>}</section><section className="card"><span className="eyebrow">A NEW CHAPTER</span><h2>Add a student</h2><p className="muted">This creates a new profile owned by your account. It does not link an existing school record.</p><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);const name=String(data.get('name'));const grade=Number(data.get('grade'));const key=JSON.stringify({name,grade});if(studentSubmission.current.key!==key)studentSubmission.current={key,id:crypto.randomUUID()};void run(async()=>{await client.addStudent({id:studentSubmission.current.id,name,grade});studentSubmission.current={key:'',id:crypto.randomUUID()};form.reset();await refresh();setNotice('Student added.');});}}><label>Student name<input name="name" required maxLength={80} placeholder="Full name"/></label><label>Grade<select name="grade">{Array.from({length:12},(_,i)=><option key={i} value={i+1}>Grade {i+1}</option>)}</select></label><button className="primary full" disabled={busy}>Add student →</button></form></section></div>}
    {view==='Applications'&&<><div className="two-column"><section className="card"><h2>Start an application</h2><p className="muted">One application per student, school and academic year.</p><form onSubmit={e=>{e.preventDefault();const key=selection+'|'+selectedSchool;if(submission.current.key!==key)submission.current={key,id:crypto.randomUUID()};void run(async()=>{await client.apply({submissionId:submission.current.id,studentId:selection,schoolId:selectedSchool,academicYear:'2026-2027'});await refresh();setNotice('Application submitted. You can follow its status below.');});}}><label>Student<select required value={selection} onChange={e=>setSelection(e.target.value)}><option value="">Choose a student</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>School<select value={selectedSchool} onChange={e=>setSelectedSchool(e.target.value)}>{schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Academic year<input value="2026–2027" readOnly/></label><button className="primary full" disabled={busy||!students.length}>Submit application →</button></form></section><section className="journey-card"><span className="eyebrow">WHAT HAPPENS NEXT</span><h2>A clear path forward.</h2>{['Submit your application','School reviews the details','A decision appears in your portal'].map((s,i)=><div className="journey-step" key={s}><span>{i+1}</span><p>{s}</p></div>)}</section></div><section className="card spaced"><h2>Your applications</h2>{applications.length?<div className="table-wrap"><table><thead><tr><th>Student</th><th>School</th><th>Submitted</th><th>Status</th></tr></thead><tbody>{applications.map(a=><tr key={a.id}><td>{students.find(s=>s.id===a.studentId)?.name??'Student'}</td><td>{schools.find(s=>s.id===a.schoolId)?.name??a.schoolId}</td><td>{new Date(a.submittedAt).toLocaleDateString()}</td><td><Badge status={a.status}/></td></tr>)}</tbody></table></div>:<Empty title="Your next chapter is unwritten." text="Submitted applications will appear here."/>}</section></>}
    {view==='Find a school'&&<div className="school-grid">{schools.map((s,i)=><section className="card school-card" key={s.id}><div className={'school-art art-'+i}><CampusArt/></div><span className="eyebrow">{s.city}</span><h2>{s.name}</h2><p className="muted">Admissions for the 2026–2027 academic year.</p><button className="secondary" onClick={()=>{setSelectedSchool(s.id);setView('Applications');}}>Apply to this school ↗</button></section>)}</div>}
    {view==='Review queue'&&<section className="card"><div className="section-heading"><h2>Recent applications</h2><span className="muted">Latest 100 submissions</span></div>{staff.length?<div className="table-wrap"><table><thead><tr><th>Student</th><th>School</th><th>Status</th><th>Decision</th></tr></thead><tbody>{staff.map(a=><tr key={a.userId+a.id}><td>{a.studentName}<small>{a.academicYear}</small></td><td>{a.schoolId}</td><td><Badge status={a.status}/></td><td>{a.status==='Submitted'?<div className="actions"><button disabled={busy} className="primary small" onClick={()=>run(async()=>{await client.decide(a,'Approved');await refresh();})}>Approve</button><button disabled={busy} className="secondary small" onClick={()=>run(async()=>{await client.decide(a,'Declined');await refresh();})}>Decline</button></div>:<span className="muted">Recorded</span>}</td></tr>)}</tbody></table></div>:<Empty title="All caught up." text="New applications will appear here."/>}</section>}
    {view==='Request activity'&&<><section className="request-flow" aria-label="Request trust boundaries">{[['Browser SDK','Session signature'],['BFF service','Session + replay checks'],['School API','Service signature + access'],['Your screen','Allowed data only']].map(([title,detail],i)=><React.Fragment key={title}>{i>0&&<span className="flow-arrow">→</span>}<div><span className="eyebrow">0{i+1}</span><strong>{title}</strong><small>{detail}</small></div></React.Fragment>)}</section><section className="card spaced"><h2>Recent activity</h2><p className="muted">Browser signatures are visible in developer tools. Backend access tokens and service secrets remain on the server.</p><div className="table-wrap"><table><thead><tr><th>Request</th><th>Result</th><th>Time</th><th>Support reference</th></tr></thead><tbody>{events.map((e,i)=><tr key={i}><td><code>{e.method} {e.route}</code></td><td><span className={e.stage==='error'?'error-text':'ok-text'}>{e.status||'—'} {e.code??'OK'}</span></td><td>{e.elapsedMs} ms</td><td><code className="trace">{e.traceId||'—'}</code></td></tr>)}</tbody></table></div></section></>}
    <footer>School Portal <span>Carefully connected. Confidently moving forward.</span></footer></main></div></div>;
}
function Stat({number,label,detail}:{number:number;label:string;detail:string}){return <section className="stat"><span className="muted">{label}</span><strong>{String(number).padStart(2,'0')}</strong><small>{detail}</small></section>;}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><span>✧</span><h3>{title}</h3><p>{text}</p></div>;}
function Badge({status}:{status:string}){return <span className={'badge '+status.toLowerCase()}>{status==='Submitted'?'In review':status}</span>;}
function StudentCard({student,balance}:{student:Student;balance?:Balance}){return <article className="student-card"><div className="student-avatar">{student.name.slice(0,1)}</div><div><h3>{student.name}</h3><p>Grade {student.grade}</p><span className="balance-label">Meal account <strong>{balance?new Intl.NumberFormat(undefined,{style:'currency',currency:balance.currency}).format(balance.balanceMinor/100):'—'}</strong></span></div></article>;}
createRoot(document.getElementById('root')!).render(<App/>);

